export const SET_TODO_INPUT = 'set_todo_input'
export const ADD_TODO = 'add_todo'
export const TICK_TODO = 'tick_todo'
export const EDIT_TODO = 'edit_todo'
export const CANCEL_EDIT = 'cancel_edit'
export const UPDATE_TODO = 'update_todo'
export const DELETE_TODO = 'delete_todo'